import type { Recipe } from "@/types/recipe"

export const SAMPLE_RECIPES: Recipe[] = [
  {
    id: "1",
    name: "Spaghetti Carbonara",
    description: "Classic Italian pasta with creamy egg sauce, crispy bacon, and Parmesan cheese",
    category: "Dinner",
    cookTime: 20,
    servings: 4,
    ingredients: ["Spaghetti", "Eggs", "Bacon", "Parmesan", "Salt", "Pepper"],
    instructions: ["Cook spaghetti", "Fry bacon", "Mix eggs with cheese", "Combine all"],
    image: "/spaghetti-carbonara.png",
    views: 245,
    rating: 4.8,
    reviews: 42,
    difficulty: "Easy",
    tags: ["Italian", "Pasta", "Quick", "Comfort Food"],
    nutrition: { calories: 580, protein: 28, carbs: 62, fat: 22 },
  },
  {
    id: "2",
    name: "Chocolate Brownies",
    description: "Fudgy and moist chocolate brownies perfect for any occasion",
    category: "Dessert",
    cookTime: 35,
    servings: 12,
    ingredients: ["Chocolate", "Butter", "Sugar", "Eggs", "Flour", "Vanilla"],
    instructions: ["Mix ingredients", "Pour in pan", "Bake until done"],
    image: "/chocolate-brownies.jpg",
    views: 189,
    rating: 4.7,
    reviews: 38,
    difficulty: "Easy",
    tags: ["Dessert", "Chocolate", "Baking"],
    nutrition: { calories: 280, protein: 4, carbs: 35, fat: 14 },
  },
  {
    id: "3",
    name: "Green Salad",
    description: "Fresh garden salad with mixed greens and vinaigrette dressing",
    category: "Lunch",
    cookTime: 10,
    servings: 2,
    ingredients: ["Lettuce", "Tomatoes", "Cucumbers", "Olive Oil", "Vinegar", "Salt"],
    instructions: ["Wash greens", "Chop vegetables", "Mix dressing", "Combine"],
    image: "/fresh-green-salad.jpg",
    views: 156,
    rating: 4.5,
    reviews: 28,
    difficulty: "Easy",
    tags: ["Salad", "Vegetarian", "Healthy", "Quick"],
    nutrition: { calories: 120, protein: 3, carbs: 8, fat: 9 },
  },
  {
    id: "4",
    name: "Fluffy Pancakes",
    description: "Fluffy pancakes perfect for breakfast with maple syrup",
    category: "Breakfast",
    cookTime: 20,
    servings: 4,
    ingredients: ["Flour", "Eggs", "Milk", "Baking Powder", "Sugar", "Butter"],
    instructions: ["Mix batter", "Heat pan", "Cook pancakes", "Serve hot"],
    image: "/fluffy-pancakes.jpg",
    views: 312,
    rating: 4.9,
    reviews: 55,
    difficulty: "Easy",
    tags: ["Breakfast", "American", "Quick", "Family-Friendly"],
    nutrition: { calories: 240, protein: 8, carbs: 42, fat: 5 },
  },
  {
    id: "5",
    name: "Grilled Salmon",
    description: "Perfectly grilled salmon fillet with lemon and herbs",
    category: "Dinner",
    cookTime: 25,
    servings: 2,
    ingredients: ["Salmon", "Lemon", "Herbs", "Olive Oil", "Salt", "Pepper"],
    instructions: ["Season fish", "Preheat grill", "Grill until done", "Serve"],
    image: "/grilled-salmon-plate.png",
    views: 278,
    rating: 4.7,
    reviews: 51,
    difficulty: "Medium",
    tags: ["Seafood", "Healthy", "Keto", "Dinner"],
    nutrition: { calories: 380, protein: 42, carbs: 0, fat: 22 },
  },
  {
    id: "6",
    name: "Tiramisu",
    description: "Classic Italian dessert with layers of coffee-soaked ladyfingers and mascarpone",
    category: "Dessert",
    cookTime: 30,
    servings: 8,
    ingredients: ["Mascarpone", "Ladyfingers", "Coffee", "Cocoa", "Sugar", "Eggs"],
    instructions: ["Prepare cream", "Soak ladyfingers", "Layer ingredients", "Chill"],
    image: "/classic-tiramisu.png",
    views: 334,
    rating: 4.8,
    reviews: 62,
    difficulty: "Medium",
    tags: ["Dessert", "Italian", "Coffee", "No-Bake"],
    nutrition: { calories: 320, protein: 6, carbs: 38, fat: 16 },
  },
  {
    id: "7",
    name: "Crispy Spring Rolls",
    description: "Golden crispy spring rolls filled with vegetables and served with sweet chili sauce",
    category: "Appetizer",
    cookTime: 25,
    servings: 6,
    ingredients: ["Spring roll wrappers", "Cabbage", "Carrots", "Bean sprouts", "Garlic", "Fish sauce", "Oil"],
    instructions: ["Prepare filling", "Roll wrappers", "Deep fry until golden", "Serve with sauce"],
    image: "/crispy-spring-rolls.jpg",
    views: 198,
    rating: 4.6,
    reviews: 34,
    difficulty: "Medium",
    tags: ["Appetizer", "Asian", "Fried", "Party"],
    nutrition: { calories: 145, protein: 3, carbs: 18, fat: 6 },
  },
  {
    id: "8",
    name: "Bruschetta al Pomodoro",
    description: "Toasted bread topped with fresh tomatoes, basil, garlic, and olive oil",
    category: "Appetizer",
    cookTime: 10,
    servings: 4,
    ingredients: ["Baguette", "Tomatoes", "Basil", "Garlic", "Olive Oil", "Balsamic Vinegar"],
    instructions: ["Toast bread", "Rub with garlic", "Top with tomato mixture", "Drizzle oil"],
    image: "/bruschetta-pomodoro.jpg",
    views: 267,
    rating: 4.7,
    reviews: 45,
    difficulty: "Easy",
    tags: ["Appetizer", "Italian", "Vegetarian", "Quick"],
    nutrition: { calories: 128, protein: 4, carbs: 19, fat: 4 },
  },
  {
    id: "9",
    name: "Loaded Nachos",
    description: "Crispy tortilla chips loaded with cheese, jalapeños, sour cream, and guacamole",
    category: "Appetizer",
    cookTime: 15,
    servings: 4,
    ingredients: ["Tortilla chips", "Cheddar cheese", "Jalapeños", "Sour cream", "Guacamole", "Salsa"],
    instructions: ["Layer chips", "Add cheese", "Bake until melted", "Top with toppings"],
    image: "/loaded-nachos.png",
    views: 289,
    rating: 4.5,
    reviews: 38,
    difficulty: "Easy",
    tags: ["Appetizer", "Mexican", "Party Food", "Cheesy"],
    nutrition: { calories: 380, protein: 12, carbs: 35, fat: 20 },
  },
  {
    id: "10",
    name: "Spinach and Feta Phyllo Triangles",
    description: "Crispy phyllo pastry filled with spinach and creamy feta cheese",
    category: "Appetizer",
    cookTime: 30,
    servings: 8,
    ingredients: ["Phyllo pastry", "Spinach", "Feta cheese", "Onion", "Garlic", "Butter", "Nutmeg"],
    instructions: ["Prepare filling", "Wrap in phyllo", "Brush with butter", "Bake until golden"],
    image: "/spinach-feta-phyllo.jpg",
    views: 176,
    rating: 4.6,
    reviews: 28,
    difficulty: "Medium",
    tags: ["Appetizer", "Mediterranean", "Vegetarian", "Elegant"],
    nutrition: { calories: 165, protein: 5, carbs: 16, fat: 8 },
  },
  {
    id: "11",
    name: "Mojito Cocktail",
    description: "Refreshing Cuban cocktail with rum, lime, mint, and soda water",
    category: "Beverage",
    cookTime: 5,
    servings: 1,
    ingredients: ["Rum", "Lime", "Mint leaves", "Sugar", "Soda water", "Ice"],
    instructions: ["Muddle mint", "Add rum and lime juice", "Add sugar and ice", "Top with soda"],
    image: "/mojito-cocktail.jpg",
    views: 223,
    rating: 4.7,
    reviews: 41,
    difficulty: "Easy",
    tags: ["Beverage", "Cocktail", "Summer", "Rum"],
    nutrition: { calories: 180, protein: 0, carbs: 16, fat: 0 },
  },
  {
    id: "12",
    name: "Green Smoothie Bowl",
    description: "Creamy green smoothie topped with granola, coconut, and fresh berries",
    category: "Beverage",
    cookTime: 5,
    servings: 1,
    ingredients: ["Spinach", "Banana", "Almond milk", "Greek yogurt", "Granola", "Berries", "Coconut"],
    instructions: ["Blend smoothie", "Pour into bowl", "Add toppings", "Serve immediately"],
    image: "/green-smoothie-bowl.png",
    views: 301,
    rating: 4.8,
    reviews: 52,
    difficulty: "Easy",
    tags: ["Beverage", "Smoothie", "Healthy", "Breakfast"],
    nutrition: { calories: 280, protein: 12, carbs: 42, fat: 8 },
  },
  {
    id: "13",
    name: "Iced Matcha Latte",
    description: "Refreshing iced matcha green tea latte with creamy oat milk",
    category: "Beverage",
    cookTime: 5,
    servings: 1,
    ingredients: ["Matcha powder", "Hot water", "Oat milk", "Honey", "Ice"],
    instructions: ["Whisk matcha", "Add hot water", "Pour milk", "Add ice"],
    image: "/iced-matcha-latte.png",
    views: 267,
    rating: 4.6,
    reviews: 38,
    difficulty: "Easy",
    tags: ["Beverage", "Tea", "Healthy", "Vegan"],
    nutrition: { calories: 140, protein: 4, carbs: 18, fat: 5 },
  },
  {
    id: "14",
    name: "Fresh Orange Juice",
    description: "Freshly squeezed orange juice with natural sweetness",
    category: "Beverage",
    cookTime: 10,
    servings: 2,
    ingredients: ["Oranges", "Lime juice"],
    instructions: ["Wash oranges", "Cut in half", "Squeeze juice", "Serve chilled"],
    image: "/fresh-orange-juice.png",
    views: 198,
    rating: 4.5,
    reviews: 31,
    difficulty: "Easy",
    tags: ["Beverage", "Juice", "Healthy", "Breakfast"],
    nutrition: { calories: 110, protein: 2, carbs: 26, fat: 0 },
  },
  {
    id: "15",
    name: "Homemade Granola",
    description: "Crunchy oat and honey granola with nuts and dried fruits",
    category: "Snack",
    cookTime: 25,
    servings: 10,
    ingredients: ["Oats", "Honey", "Almonds", "Pecans", "Dried cranberries", "Coconut oil", "Cinnamon"],
    instructions: ["Mix ingredients", "Spread on baking sheet", "Bake until golden", "Cool and store"],
    image: "/homemade-granola.jpg",
    views: 245,
    rating: 4.7,
    reviews: 42,
    difficulty: "Easy",
    tags: ["Snack", "Breakfast", "Healthy", "No-Bake Option"],
    nutrition: { calories: 280, protein: 8, carbs: 32, fat: 14 },
  },
  {
    id: "16",
    name: "Homemade Protein Balls",
    description: "No-bake energy balls with peanut butter, chocolate, and oats",
    category: "Snack",
    cookTime: 10,
    servings: 12,
    ingredients: ["Peanut butter", "Oats", "Honey", "Dark chocolate", "Coconut oil"],
    instructions: ["Mix ingredients", "Roll into balls", "Refrigerate", "Serve"],
    image: "/protein-energy-balls.jpg",
    views: 289,
    rating: 4.8,
    reviews: 48,
    difficulty: "Easy",
    tags: ["Snack", "Energy", "No-Bake", "Healthy"],
    nutrition: { calories: 160, protein: 6, carbs: 18, fat: 8 },
  },
  {
    id: "17",
    name: "Spicy Roasted Chickpeas",
    description: "Crispy roasted chickpeas with paprika and cayenne pepper",
    category: "Snack",
    cookTime: 30,
    servings: 4,
    ingredients: ["Chickpeas", "Paprika", "Cayenne", "Garlic powder", "Olive oil", "Salt"],
    instructions: ["Drain and dry chickpeas", "Toss with seasonings", "Roast until crispy", "Cool"],
    image: "/roasted-chickpeas.jpg",
    views: 167,
    rating: 4.4,
    reviews: 25,
    difficulty: "Easy",
    tags: ["Snack", "Vegetarian", "Healthy", "Spicy"],
    nutrition: { calories: 140, protein: 5, carbs: 19, fat: 4 },
  },
  {
    id: "18",
    name: "Veggie & Hummus Platter",
    description: "Fresh vegetable medley served with creamy hummus dip",
    category: "Snack",
    cookTime: 15,
    servings: 4,
    ingredients: ["Carrots", "Celery", "Bell peppers", "Cherry tomatoes", "Hummus", "Olive oil", "Lemon"],
    instructions: ["Wash vegetables", "Cut into sticks", "Prepare hummus", "Arrange on platter"],
    image: "/veggie-hummus-platter.jpg",
    views: 203,
    rating: 4.6,
    reviews: 36,
    difficulty: "Easy",
    tags: ["Snack", "Vegetarian", "Healthy", "Party"],
    nutrition: { calories: 95, protein: 4, carbs: 14, fat: 3 },
  },
]
